services:
  - type: web
    name: gothic-md-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: SESSION_ID
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: IMGBB_API_KEY
        sync: false
      - key: REMOVEBG_API_KEY
        sync: false
      - key: OCR_API_KEY
        sync: false
      - key: OWNER_NAME
        value: KINGSLEY-XMD
      - key: CHANNEL_ID
        value: 0029Vb6zdPc5vKAAAY0imG2R
      - key: CHANNEL_REACTIONS
        value: "❤️,🔥,💯,⚡,🎯,💀,👑,🚀"
      - key: PREFIX
        value: "."
      - key: BOT_NAME
        value: GOTHIC MD BOT
      - key: BOT_IMAGE
        value: https://i.ibb.co/zVyCpvQX/ERFAN-MD.jpg
      - key: AUTO_JOIN_CHANNEL
        value: "true"
      - key: AUTO_REACT_CHANNEL
        value: "true"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
